[tool.poetry]
name = "jupyter-notebook"
version = "0.1.1"
description = "Visualisation of square wave program using Jupyter Notebooks"
authors = ["Nathan Young"]
license = "Apache-2.0"
readme = "README.md"
packages = []


[tool.poetry.dependencies]
python = "^3.11"
rp2040-pio-emulator = "==0.86.0"
jupyter = "==1.1.1"
seaborn = "==0.13.2"
vcdvcd = "^2.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
